### ISSUE TITLE
Failure in populate machine file locally

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-pdsh-machines#1]
<code>
TASK [ansible-role-pdsh-machines : populate machines file locally] *************
fatal: [install2]: FAILED! => {"failed": true, "msg": "'ansible.vars.hostvars.HostVars object' has no attribute u'groups.compute'"}
</code>

Possibly due to the recent ansible update from EPEL (see https://github.com/CSC-IT-Center-for-Science/fgci-ansible/issues/117 )

**Comment by martbhell** [comment]
Should be fixed by @A1ve5 in a8eeee485e68c0afde437d105aeaeaf51a16cf7d - we'll update requirements.yml next week.

**Comment by martbhell** [comment]
As far as I can see this has been fixed. Not seeing these errors when running pdsh-machines role on our install node.
Are you still seeing these errors @jabl ?

**Comment by jabl** [comment]
Seems to work now. Thanks!
